# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:
#{ cabal, aeson, bifunctors, classyPrelude
#, configurator, either, errors, groups, hourglass, hspec, lens
#, MonadCatchIOTransformers, mtl, networkBitcoin
#, optparseApplicative, safe, snapCore, snapServer, sqliteSimple
#, text, time, transformers
#}:

with haskellPackages; cabal.mkDerivation (self: {
  pname = "quixotic";
  version = "0.1";
  src = "./.";
  isLibrary = true;
  isExecutable = true;
  #buildTools = [ cabalInstall ];
  buildDepends = [
    aeson bifunctors classyPrelude configurator either
    errors groups hourglass lens MonadCatchIOTransformers mtl
    networkBitcoin optparseApplicative safe snapCore snapServer
    sqliteSimple text time transformers
  ];
  testDepends = [ aeson hspec text time ];
  meta = {
    description = "The Quixotic Collaboration Platform";
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
