Hi $greet_name$!

$from_email$ has invited you to join the "$project_name$" project on aftok.com.

If you don't have an aftok.com account yet, click the link below to sign up
and automatically accept the invitation:

$signup_url$

If you already have an aftok.com account, sign in and accept the invitation
from here:

$accept_url$

If you have any questions, reach out to $from_email$ for more details about the project.

- The Aftok Team
